name: gold_chart_app
description: A Flutter app showing gold price chart.

publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true